/**
 * @fileoverview gRPC-Web generated client stub for auction
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.1
// source: proto/auction.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.auction = require('./auction_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.auction.AuctionServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.auction.AuctionServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auction.RegisterRequest,
 *   !proto.auction.User>}
 */
const methodDescriptor_AuctionService_Register = new grpc.web.MethodDescriptor(
  '/auction.AuctionService/Register',
  grpc.web.MethodType.UNARY,
  proto.auction.RegisterRequest,
  proto.auction.User,
  /**
   * @param {!proto.auction.RegisterRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auction.User.deserializeBinary
);


/**
 * @param {!proto.auction.RegisterRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auction.User)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auction.User>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServiceClient.prototype.register =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auction.AuctionService/Register',
      request,
      metadata || {},
      methodDescriptor_AuctionService_Register,
      callback);
};


/**
 * @param {!proto.auction.RegisterRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auction.User>}
 *     Promise that resolves to the response
 */
proto.auction.AuctionServicePromiseClient.prototype.register =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auction.AuctionService/Register',
      request,
      metadata || {},
      methodDescriptor_AuctionService_Register);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auction.LoginRequest,
 *   !proto.auction.LoginResponse>}
 */
const methodDescriptor_AuctionService_Login = new grpc.web.MethodDescriptor(
  '/auction.AuctionService/Login',
  grpc.web.MethodType.UNARY,
  proto.auction.LoginRequest,
  proto.auction.LoginResponse,
  /**
   * @param {!proto.auction.LoginRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auction.LoginResponse.deserializeBinary
);


/**
 * @param {!proto.auction.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auction.LoginResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auction.LoginResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServiceClient.prototype.login =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auction.AuctionService/Login',
      request,
      metadata || {},
      methodDescriptor_AuctionService_Login,
      callback);
};


/**
 * @param {!proto.auction.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auction.LoginResponse>}
 *     Promise that resolves to the response
 */
proto.auction.AuctionServicePromiseClient.prototype.login =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auction.AuctionService/Login',
      request,
      metadata || {},
      methodDescriptor_AuctionService_Login);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auction.GetUserRequest,
 *   !proto.auction.User>}
 */
const methodDescriptor_AuctionService_GetUser = new grpc.web.MethodDescriptor(
  '/auction.AuctionService/GetUser',
  grpc.web.MethodType.UNARY,
  proto.auction.GetUserRequest,
  proto.auction.User,
  /**
   * @param {!proto.auction.GetUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auction.User.deserializeBinary
);


/**
 * @param {!proto.auction.GetUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auction.User)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auction.User>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServiceClient.prototype.getUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auction.AuctionService/GetUser',
      request,
      metadata || {},
      methodDescriptor_AuctionService_GetUser,
      callback);
};


/**
 * @param {!proto.auction.GetUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auction.User>}
 *     Promise that resolves to the response
 */
proto.auction.AuctionServicePromiseClient.prototype.getUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auction.AuctionService/GetUser',
      request,
      metadata || {},
      methodDescriptor_AuctionService_GetUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auction.ListUsersRequest,
 *   !proto.auction.ListUsersResponse>}
 */
const methodDescriptor_AuctionService_ListUsers = new grpc.web.MethodDescriptor(
  '/auction.AuctionService/ListUsers',
  grpc.web.MethodType.UNARY,
  proto.auction.ListUsersRequest,
  proto.auction.ListUsersResponse,
  /**
   * @param {!proto.auction.ListUsersRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auction.ListUsersResponse.deserializeBinary
);


/**
 * @param {!proto.auction.ListUsersRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auction.ListUsersResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auction.ListUsersResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServiceClient.prototype.listUsers =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auction.AuctionService/ListUsers',
      request,
      metadata || {},
      methodDescriptor_AuctionService_ListUsers,
      callback);
};


/**
 * @param {!proto.auction.ListUsersRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auction.ListUsersResponse>}
 *     Promise that resolves to the response
 */
proto.auction.AuctionServicePromiseClient.prototype.listUsers =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auction.AuctionService/ListUsers',
      request,
      metadata || {},
      methodDescriptor_AuctionService_ListUsers);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auction.CreateItemRequest,
 *   !proto.auction.Item>}
 */
const methodDescriptor_AuctionService_CreateItem = new grpc.web.MethodDescriptor(
  '/auction.AuctionService/CreateItem',
  grpc.web.MethodType.UNARY,
  proto.auction.CreateItemRequest,
  proto.auction.Item,
  /**
   * @param {!proto.auction.CreateItemRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auction.Item.deserializeBinary
);


/**
 * @param {!proto.auction.CreateItemRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auction.Item)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auction.Item>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServiceClient.prototype.createItem =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auction.AuctionService/CreateItem',
      request,
      metadata || {},
      methodDescriptor_AuctionService_CreateItem,
      callback);
};


/**
 * @param {!proto.auction.CreateItemRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auction.Item>}
 *     Promise that resolves to the response
 */
proto.auction.AuctionServicePromiseClient.prototype.createItem =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auction.AuctionService/CreateItem',
      request,
      metadata || {},
      methodDescriptor_AuctionService_CreateItem);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auction.UpdateItemRequest,
 *   !proto.auction.Item>}
 */
const methodDescriptor_AuctionService_UpdateItem = new grpc.web.MethodDescriptor(
  '/auction.AuctionService/UpdateItem',
  grpc.web.MethodType.UNARY,
  proto.auction.UpdateItemRequest,
  proto.auction.Item,
  /**
   * @param {!proto.auction.UpdateItemRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auction.Item.deserializeBinary
);


/**
 * @param {!proto.auction.UpdateItemRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auction.Item)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auction.Item>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServiceClient.prototype.updateItem =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auction.AuctionService/UpdateItem',
      request,
      metadata || {},
      methodDescriptor_AuctionService_UpdateItem,
      callback);
};


/**
 * @param {!proto.auction.UpdateItemRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auction.Item>}
 *     Promise that resolves to the response
 */
proto.auction.AuctionServicePromiseClient.prototype.updateItem =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auction.AuctionService/UpdateItem',
      request,
      metadata || {},
      methodDescriptor_AuctionService_UpdateItem);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auction.GetItemRequest,
 *   !proto.auction.Item>}
 */
const methodDescriptor_AuctionService_GetItem = new grpc.web.MethodDescriptor(
  '/auction.AuctionService/GetItem',
  grpc.web.MethodType.UNARY,
  proto.auction.GetItemRequest,
  proto.auction.Item,
  /**
   * @param {!proto.auction.GetItemRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auction.Item.deserializeBinary
);


/**
 * @param {!proto.auction.GetItemRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auction.Item)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auction.Item>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServiceClient.prototype.getItem =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auction.AuctionService/GetItem',
      request,
      metadata || {},
      methodDescriptor_AuctionService_GetItem,
      callback);
};


/**
 * @param {!proto.auction.GetItemRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auction.Item>}
 *     Promise that resolves to the response
 */
proto.auction.AuctionServicePromiseClient.prototype.getItem =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auction.AuctionService/GetItem',
      request,
      metadata || {},
      methodDescriptor_AuctionService_GetItem);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auction.ListItemsRequest,
 *   !proto.auction.ListItemsResponse>}
 */
const methodDescriptor_AuctionService_ListItems = new grpc.web.MethodDescriptor(
  '/auction.AuctionService/ListItems',
  grpc.web.MethodType.UNARY,
  proto.auction.ListItemsRequest,
  proto.auction.ListItemsResponse,
  /**
   * @param {!proto.auction.ListItemsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auction.ListItemsResponse.deserializeBinary
);


/**
 * @param {!proto.auction.ListItemsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auction.ListItemsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auction.ListItemsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServiceClient.prototype.listItems =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auction.AuctionService/ListItems',
      request,
      metadata || {},
      methodDescriptor_AuctionService_ListItems,
      callback);
};


/**
 * @param {!proto.auction.ListItemsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auction.ListItemsResponse>}
 *     Promise that resolves to the response
 */
proto.auction.AuctionServicePromiseClient.prototype.listItems =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auction.AuctionService/ListItems',
      request,
      metadata || {},
      methodDescriptor_AuctionService_ListItems);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auction.ListMyItemsRequest,
 *   !proto.auction.ListItemsResponse>}
 */
const methodDescriptor_AuctionService_ListMyItems = new grpc.web.MethodDescriptor(
  '/auction.AuctionService/ListMyItems',
  grpc.web.MethodType.UNARY,
  proto.auction.ListMyItemsRequest,
  proto.auction.ListItemsResponse,
  /**
   * @param {!proto.auction.ListMyItemsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auction.ListItemsResponse.deserializeBinary
);


/**
 * @param {!proto.auction.ListMyItemsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auction.ListItemsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auction.ListItemsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServiceClient.prototype.listMyItems =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auction.AuctionService/ListMyItems',
      request,
      metadata || {},
      methodDescriptor_AuctionService_ListMyItems,
      callback);
};


/**
 * @param {!proto.auction.ListMyItemsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auction.ListItemsResponse>}
 *     Promise that resolves to the response
 */
proto.auction.AuctionServicePromiseClient.prototype.listMyItems =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auction.AuctionService/ListMyItems',
      request,
      metadata || {},
      methodDescriptor_AuctionService_ListMyItems);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auction.CancelItemRequest,
 *   !proto.auction.Item>}
 */
const methodDescriptor_AuctionService_CancelItem = new grpc.web.MethodDescriptor(
  '/auction.AuctionService/CancelItem',
  grpc.web.MethodType.UNARY,
  proto.auction.CancelItemRequest,
  proto.auction.Item,
  /**
   * @param {!proto.auction.CancelItemRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auction.Item.deserializeBinary
);


/**
 * @param {!proto.auction.CancelItemRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auction.Item)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auction.Item>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServiceClient.prototype.cancelItem =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auction.AuctionService/CancelItem',
      request,
      metadata || {},
      methodDescriptor_AuctionService_CancelItem,
      callback);
};


/**
 * @param {!proto.auction.CancelItemRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auction.Item>}
 *     Promise that resolves to the response
 */
proto.auction.AuctionServicePromiseClient.prototype.cancelItem =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auction.AuctionService/CancelItem',
      request,
      metadata || {},
      methodDescriptor_AuctionService_CancelItem);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auction.PlaceBidRequest,
 *   !proto.auction.PlaceBidResponse>}
 */
const methodDescriptor_AuctionService_PlaceBid = new grpc.web.MethodDescriptor(
  '/auction.AuctionService/PlaceBid',
  grpc.web.MethodType.UNARY,
  proto.auction.PlaceBidRequest,
  proto.auction.PlaceBidResponse,
  /**
   * @param {!proto.auction.PlaceBidRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auction.PlaceBidResponse.deserializeBinary
);


/**
 * @param {!proto.auction.PlaceBidRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auction.PlaceBidResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auction.PlaceBidResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServiceClient.prototype.placeBid =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auction.AuctionService/PlaceBid',
      request,
      metadata || {},
      methodDescriptor_AuctionService_PlaceBid,
      callback);
};


/**
 * @param {!proto.auction.PlaceBidRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auction.PlaceBidResponse>}
 *     Promise that resolves to the response
 */
proto.auction.AuctionServicePromiseClient.prototype.placeBid =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auction.AuctionService/PlaceBid',
      request,
      metadata || {},
      methodDescriptor_AuctionService_PlaceBid);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auction.GetBidsRequest,
 *   !proto.auction.GetBidsResponse>}
 */
const methodDescriptor_AuctionService_GetBids = new grpc.web.MethodDescriptor(
  '/auction.AuctionService/GetBids',
  grpc.web.MethodType.UNARY,
  proto.auction.GetBidsRequest,
  proto.auction.GetBidsResponse,
  /**
   * @param {!proto.auction.GetBidsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auction.GetBidsResponse.deserializeBinary
);


/**
 * @param {!proto.auction.GetBidsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auction.GetBidsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auction.GetBidsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServiceClient.prototype.getBids =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auction.AuctionService/GetBids',
      request,
      metadata || {},
      methodDescriptor_AuctionService_GetBids,
      callback);
};


/**
 * @param {!proto.auction.GetBidsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auction.GetBidsResponse>}
 *     Promise that resolves to the response
 */
proto.auction.AuctionServicePromiseClient.prototype.getBids =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auction.AuctionService/GetBids',
      request,
      metadata || {},
      methodDescriptor_AuctionService_GetBids);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auction.GetMyBidsRequest,
 *   !proto.auction.GetBidsResponse>}
 */
const methodDescriptor_AuctionService_GetMyBids = new grpc.web.MethodDescriptor(
  '/auction.AuctionService/GetMyBids',
  grpc.web.MethodType.UNARY,
  proto.auction.GetMyBidsRequest,
  proto.auction.GetBidsResponse,
  /**
   * @param {!proto.auction.GetMyBidsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auction.GetBidsResponse.deserializeBinary
);


/**
 * @param {!proto.auction.GetMyBidsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auction.GetBidsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auction.GetBidsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServiceClient.prototype.getMyBids =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auction.AuctionService/GetMyBids',
      request,
      metadata || {},
      methodDescriptor_AuctionService_GetMyBids,
      callback);
};


/**
 * @param {!proto.auction.GetMyBidsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auction.GetBidsResponse>}
 *     Promise that resolves to the response
 */
proto.auction.AuctionServicePromiseClient.prototype.getMyBids =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auction.AuctionService/GetMyBids',
      request,
      metadata || {},
      methodDescriptor_AuctionService_GetMyBids);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auction.StreamBidsRequest,
 *   !proto.auction.StreamBidsResponse>}
 */
const methodDescriptor_AuctionService_StreamBids = new grpc.web.MethodDescriptor(
  '/auction.AuctionService/StreamBids',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.auction.StreamBidsRequest,
  proto.auction.StreamBidsResponse,
  /**
   * @param {!proto.auction.StreamBidsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auction.StreamBidsResponse.deserializeBinary
);


/**
 * @param {!proto.auction.StreamBidsRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.auction.StreamBidsResponse>}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServiceClient.prototype.streamBids =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/auction.AuctionService/StreamBids',
      request,
      metadata || {},
      methodDescriptor_AuctionService_StreamBids);
};


/**
 * @param {!proto.auction.StreamBidsRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.auction.StreamBidsResponse>}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServicePromiseClient.prototype.streamBids =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/auction.AuctionService/StreamBids',
      request,
      metadata || {},
      methodDescriptor_AuctionService_StreamBids);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auction.StreamAuctionRequest,
 *   !proto.auction.AuctionUpdate>}
 */
const methodDescriptor_AuctionService_StreamAuction = new grpc.web.MethodDescriptor(
  '/auction.AuctionService/StreamAuction',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.auction.StreamAuctionRequest,
  proto.auction.AuctionUpdate,
  /**
   * @param {!proto.auction.StreamAuctionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auction.AuctionUpdate.deserializeBinary
);


/**
 * @param {!proto.auction.StreamAuctionRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.auction.AuctionUpdate>}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServiceClient.prototype.streamAuction =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/auction.AuctionService/StreamAuction',
      request,
      metadata || {},
      methodDescriptor_AuctionService_StreamAuction);
};


/**
 * @param {!proto.auction.StreamAuctionRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.auction.AuctionUpdate>}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServicePromiseClient.prototype.streamAuction =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/auction.AuctionService/StreamAuction',
      request,
      metadata || {},
      methodDescriptor_AuctionService_StreamAuction);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auction.CreateOrderRequest,
 *   !proto.auction.Order>}
 */
const methodDescriptor_AuctionService_CreateOrder = new grpc.web.MethodDescriptor(
  '/auction.AuctionService/CreateOrder',
  grpc.web.MethodType.UNARY,
  proto.auction.CreateOrderRequest,
  proto.auction.Order,
  /**
   * @param {!proto.auction.CreateOrderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auction.Order.deserializeBinary
);


/**
 * @param {!proto.auction.CreateOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auction.Order)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auction.Order>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServiceClient.prototype.createOrder =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auction.AuctionService/CreateOrder',
      request,
      metadata || {},
      methodDescriptor_AuctionService_CreateOrder,
      callback);
};


/**
 * @param {!proto.auction.CreateOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auction.Order>}
 *     Promise that resolves to the response
 */
proto.auction.AuctionServicePromiseClient.prototype.createOrder =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auction.AuctionService/CreateOrder',
      request,
      metadata || {},
      methodDescriptor_AuctionService_CreateOrder);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auction.GetOrderRequest,
 *   !proto.auction.Order>}
 */
const methodDescriptor_AuctionService_GetOrder = new grpc.web.MethodDescriptor(
  '/auction.AuctionService/GetOrder',
  grpc.web.MethodType.UNARY,
  proto.auction.GetOrderRequest,
  proto.auction.Order,
  /**
   * @param {!proto.auction.GetOrderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auction.Order.deserializeBinary
);


/**
 * @param {!proto.auction.GetOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auction.Order)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auction.Order>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServiceClient.prototype.getOrder =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auction.AuctionService/GetOrder',
      request,
      metadata || {},
      methodDescriptor_AuctionService_GetOrder,
      callback);
};


/**
 * @param {!proto.auction.GetOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auction.Order>}
 *     Promise that resolves to the response
 */
proto.auction.AuctionServicePromiseClient.prototype.getOrder =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auction.AuctionService/GetOrder',
      request,
      metadata || {},
      methodDescriptor_AuctionService_GetOrder);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auction.ListOrdersRequest,
 *   !proto.auction.ListOrdersResponse>}
 */
const methodDescriptor_AuctionService_ListOrders = new grpc.web.MethodDescriptor(
  '/auction.AuctionService/ListOrders',
  grpc.web.MethodType.UNARY,
  proto.auction.ListOrdersRequest,
  proto.auction.ListOrdersResponse,
  /**
   * @param {!proto.auction.ListOrdersRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auction.ListOrdersResponse.deserializeBinary
);


/**
 * @param {!proto.auction.ListOrdersRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auction.ListOrdersResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auction.ListOrdersResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServiceClient.prototype.listOrders =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auction.AuctionService/ListOrders',
      request,
      metadata || {},
      methodDescriptor_AuctionService_ListOrders,
      callback);
};


/**
 * @param {!proto.auction.ListOrdersRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auction.ListOrdersResponse>}
 *     Promise that resolves to the response
 */
proto.auction.AuctionServicePromiseClient.prototype.listOrders =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auction.AuctionService/ListOrders',
      request,
      metadata || {},
      methodDescriptor_AuctionService_ListOrders);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auction.UpdateOrderStatusRequest,
 *   !proto.auction.Order>}
 */
const methodDescriptor_AuctionService_UpdateOrderStatus = new grpc.web.MethodDescriptor(
  '/auction.AuctionService/UpdateOrderStatus',
  grpc.web.MethodType.UNARY,
  proto.auction.UpdateOrderStatusRequest,
  proto.auction.Order,
  /**
   * @param {!proto.auction.UpdateOrderStatusRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auction.Order.deserializeBinary
);


/**
 * @param {!proto.auction.UpdateOrderStatusRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auction.Order)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auction.Order>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auction.AuctionServiceClient.prototype.updateOrderStatus =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auction.AuctionService/UpdateOrderStatus',
      request,
      metadata || {},
      methodDescriptor_AuctionService_UpdateOrderStatus,
      callback);
};


/**
 * @param {!proto.auction.UpdateOrderStatusRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auction.Order>}
 *     Promise that resolves to the response
 */
proto.auction.AuctionServicePromiseClient.prototype.updateOrderStatus =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auction.AuctionService/UpdateOrderStatus',
      request,
      metadata || {},
      methodDescriptor_AuctionService_UpdateOrderStatus);
};


module.exports = proto.auction;

